name: Deploy to LWS FTP

on:
  push:
    branches:
      - master # S'exécute à chaque push sur la branche principale

jobs:
  ftp-deploy:
    name: FTP Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Préparation des fichiers (Renommage portail.html en index.html)
        run: |
          if [ -f "portail.html" ]; then
            mv portail.html index.html
          fi

      - name: Synchronisation FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          exclude: |
            **/.git*
            **/.git*/**
            .github/**
            **/*.py
            **/*.txt
            clean_students*.json
            *.xlsx
            scratch_*
            README.md
